# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Fernando Cristobal Cordero
# Description of the Site
description: Architetto e designer
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Architetto, Fernando Cristobal Cordero, Design, Curriculum Vitae
# URL for the Image of custom Favicon
favicon-url: /assets/images/logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://arch-cordero.github.io/assets/images/hero.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: arch.cordero@gmail.com
linkedin_username: fernandocristobalcordero
github_username:  arch-cordero
behance_username: studiogargano51

# Google Analytics
google-analytics: /

# Name of the Author
author-name: Architetto Fernando Cristobal Cordero
# URL for the Image of the Author
author-image: /assets/images/profile.jpeg
# 60 Words About the Author
author-about: "Fernando Cristobal Cordero è specializzato in progetti architettonici, urbanistica, servizi tecnici, gestionali e ambientali. Collabora con un team di professionisti altamente qualificati, utilizzando le più moderne tecnologie. È in grado di sviluppare e realizzare progetti, dal concept fino al completamento, seguendo gli standard di settore e ponendo particolare attenzione al raggiungimento della sostenibilità. Vanta molti anni di esperienza nella gestione e nell'elaborazione di cartografia informatizzata, studi di fattibilità, ricerche e rilievi del territorio, progettazione edilizia, costruzione e pianificazione stradale, oltre alla pianificazione ambientale e paesaggistica con tutti i dettagli necessari. Si avvale di un team completo di professionisti, che comprende architetti, ingegneri civili, ingegneri strutturali, ingegneri impiantisti, ingegneri ambientali, biologi, esperti in gestione contabile e economisti. Gestisce il project management e coordina tutte le attività, dalla pianificazione all'approvazione e valutazione, dalla supervisione dei lavori fino alla realizzazione del design d’interni. Opera principalmente nei settori residenziale, commerciale, educativo, del restauro, dell’urbanistica, nonché nei settori artistico e del tempo libero."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/arch-cordero

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

date_locale: "it"
default_locale: "it"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
